version: '3.8'
services:
  db-test:
    env_file: .env.test
    image: postgres
    ports:
      - "5433:5432"
  db:
    env_file: .env.development
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p 3000 -b '0.0.0.0' & ruby ./bin/webpack-dev-server"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - db-test
    env_file: .env.development
volumes:
  postgres: